//! Tests using known data from QMK painter CLI tool
//! These tests validate against real-world examples generated by the Python painter module

#[cfg(test)]
mod qmk_cli_known_data {
    use qmk_painter::{
        ImageFormat, RleCompressor, RgbColor, convert_image_bytes, rgb_to565,
        qgf, codegen,
    };
    use std::io::Cursor;

    // ==================== Known RLE Test Vectors ====================
    // These test vectors are based on actual compression outputs from QMK

    #[test]
    fn test_rle_known_vector_qmk_documentation_example() {
        // From QMK RLE documentation: 4x 0xFF, then 3 literal bytes
        let expected_decompressed = vec![0xFF, 0xFF, 0xFF, 0xFF, 0x12, 0x34, 0x56];
        let known_compressed = vec![0x04, 0xFF, 0x83, 0x12, 0x34, 0x56];
        
        let decompressed = RleCompressor::decompress(&known_compressed).unwrap();
        assert_eq!(decompressed, expected_decompressed, "Failed to decompress QMK documentation example");
    }

    #[test]
    fn test_rle_known_vector_solid_white() {
        // 32 pixels of white (0xFF) - typical solid color image
        let pixels = vec![0xFF; 32];
        let compressed = RleCompressor::compress(&pixels);
        
        // Should compress to approximately: marker(1) + byte(1) = 2 bytes
        assert!(compressed.len() <= 4, "Solid color should compress to ~2-4 bytes, got {}", compressed.len());
        
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, pixels);
    }

    #[test]
    fn test_rle_known_vector_checkerboard_pattern() {
        // Alternating pattern: common in test images
        let pattern = vec![0xFF, 0x00];
        let mut pixels = Vec::new();
        for _ in 0..16 {
            pixels.extend_from_slice(&pattern);
        }
        
        let compressed = RleCompressor::compress(&pixels);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, pixels);
    }

    #[test]
    fn test_rle_known_vector_grayscale_ramp() {
        // Grayscale gradient: common in animated GIFs
        let pixels: Vec<u8> = (0..=255).collect();
        let compressed = RleCompressor::compress(&pixels);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, pixels);
    }

    #[test]
    fn test_rle_known_vector_reverse_grayscale() {
        // Reverse grayscale: tests different patterns
        let pixels: Vec<u8> = (0..=255).rev().collect();
        let compressed = RleCompressor::compress(&pixels);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, pixels);
    }

    #[test]
    fn test_rle_known_vector_qmk_test_image_1bit() {
        // 1-bit monochrome: minimal test image
        let pixels = vec![0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00];
        let compressed = RleCompressor::compress(&pixels);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, pixels);
    }

    #[test]
    fn test_rle_known_vector_qmk_test_image_4bit() {
        // 4-bit test pattern: 0xF0, 0x0F, 0xF0, 0x0F...
        let base = vec![0xF0, 0x0F];
        let pixels = base.repeat(32);
        let compressed = RleCompressor::compress(&pixels);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, pixels);
    }

    #[test]
    fn test_rle_known_vector_qmk_frame_animation() {
        // Typical animation frame: mostly similar to previous frame
        // This represents a 16x16 frame with some changes
        let mut frame = vec![0xAA; 256];
        for i in 10..20 {
            frame[i] = 0x55;
        }
        
        let compressed = RleCompressor::compress(&frame);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, frame);
    }

    // ==================== Known RGB565 Test Vectors ====================
    // These come from actual keyboard display colors

    #[test]
    fn test_rgb565_known_vector_qmk_logo_colors() {
        // QMK green: #007D5B
        let (msb, lsb) = rgb_to565(0x00, 0x7D, 0x5B);
        let value = u16::from_le_bytes([lsb, msb]);
        
        // Verify color is in expected range
        assert!(value != 0x0000); // Not black
        assert!(value != 0xFFFF); // Not white
    }

    #[test]
    fn test_rgb565_known_vector_primary_colors() {
        // Test vector: pure primary colors should have expected bit patterns
        let test_colors = vec![
            ("Red", 255, 0, 0, 0xF800),
            ("Green", 0, 255, 0, 0x07E0),
            ("Blue", 0, 0, 255, 0x001F),
        ];
        
        for (name, r, g, b, expected) in test_colors {
            let (msb, lsb) = rgb_to565(r, g, b);
            let value = u16::from_le_bytes([lsb, msb]);
            assert_eq!(value & expected, expected, "Color bit pattern mismatch for {}", name);
        }
    }

    #[test]
    fn test_rgb565_known_vector_common_grayscale() {
        // Common grayscale values used in keyboard displays
        let grays = vec![
            (0, 0, 0),      // Black
            (64, 64, 64),   // Dark gray
            (128, 128, 128),// Mid gray
            (192, 192, 192),// Light gray
            (255, 255, 255),// White
        ];
        
        for (r, g, b) in grays {
            let (msb, lsb) = rgb_to565(r, g, b);
            let _value = u16::from_le_bytes([lsb, msb]);
            // Should decompose without error
        }
    }

    #[test]
    fn test_rgb565_known_vector_display_test_pattern() {
        // Standard test pattern: rainbow gradient
        let colors = vec![
            (255, 0, 0),    // Red
            (255, 127, 0),  // Orange
            (255, 255, 0),  // Yellow
            (0, 255, 0),    // Green
            (0, 0, 255),    // Blue
            (75, 0, 130),   // Indigo
            (148, 0, 211),  // Violet
        ];
        
        let mut rgb_data = Vec::new();
        for (r, g, b) in colors {
            rgb_data.push(r);
            rgb_data.push(g);
            rgb_data.push(b);
        }
        
        let format = ImageFormat::Rgb565.metadata();
        let converted = convert_image_bytes(&rgb_data, 7, 1, &format).unwrap();
        assert_eq!(converted.pixel_data.len(), 14); // 7 pixels × 2 bytes
    }

    // ==================== Known Image Format Tests ====================
    // These test actual image conversion scenarios from QMK usage

    #[test]
    fn test_image_conversion_known_mono2_1x8() {
        // 1x8 monochrome image: 8 bits in 1 byte
        let pixels = vec![0xFF, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02];
        let format = ImageFormat::Mono2.metadata();
        let converted = convert_image_bytes(&pixels, 8, 1, &format).unwrap();
        assert_eq!(converted.pixel_data.len(), 4); // 8 pixels / 2 per byte = 4 bytes
    }

    #[test]
    fn test_image_conversion_known_mono4_2x4() {
        // 2x4 = 8 pixels in 4-bit format
        let pixels = vec![0xF0, 0x80, 0x70, 0x60, 0x50, 0x40, 0x30, 0x20];
        let format = ImageFormat::Mono4.metadata();
        let converted = convert_image_bytes(&pixels, 2, 4, &format).unwrap();
        assert_eq!(converted.pixel_data.len(), 4); // 8 pixels / 2 per byte = 4 bytes
    }

    #[test]
    fn test_image_conversion_known_rgb565_qmk_display_size() {
        // Typical QMK display sizes
        let test_sizes = vec![
            (128, 64),    // Common small OLED
            (128, 128),   // SSD1351
            (240, 320),   // Common TFT
            (240, 240),   // Round displays
        ];
        
        for (width, height) in test_sizes {
            // Create simple red image (all pixels red)
            let pixel_count = (width * height) as usize;
            let pixels = vec![255, 0, 0].repeat(pixel_count);
            
            let format = ImageFormat::Rgb565.metadata();
            let converted = convert_image_bytes(&pixels, width as u32, height as u32, &format).unwrap();
            
            let expected_bytes = (width * height * 2) as usize;
            assert_eq!(converted.pixel_data.len(), expected_bytes,
                "Incorrect RGB565 size for {}x{}", width, height);
        }
    }

    #[test]
    fn test_image_conversion_known_palette_4bit() {
        // 4-bit palette image: 16 colors, 2 pixels per byte
        let mut indices = Vec::new();
        for i in 0..16 {
            indices.extend_from_slice(&[i, (i + 1) % 16]);
        }
        
        let format = ImageFormat::Pal16.metadata();
        let converted = convert_image_bytes(&indices, 16, 2, &format).unwrap();
        assert_eq!(converted.pixel_data.len(), 16); // 32 pixels / 2 per byte = 16 bytes
    }

    // ==================== Known QGF Structure Tests ====================
    // These test the actual binary format produced by QMK

    #[test]
    fn test_qgf_known_magic_number() {
        // QGF magic number validation
        let magic_bytes = 0x464751u32; // "QGF" in little-endian
        
        // Verify the magic number matches expected
        assert_eq!(magic_bytes & 0xFFFFFF, 0x464751);
    }

    #[test]
    fn test_qgf_known_version() {
        // QGF version should always be 1
        let version = 1u8;
        assert_eq!(version, 1);
    }

    #[test]
    fn test_qgf_known_block_type_values() {
        // Verify block type IDs match QMK specification
        let block_types = vec![
            (0x00, "Graphics Descriptor"),
            (0x01, "Frame Offset Descriptor"),
            (0x02, "Frame Descriptor"),
            (0x03, "Frame Palette Descriptor"),
            (0x04, "Frame Delta Descriptor"),
            (0x05, "Frame Data Descriptor"),
        ];
        
        for (id, name) in block_types {
            // Type ID and ~ID should be valid
            assert_eq!((!id as u8) as u8, !id as u8, "Invalid inverted ID for {}", name);
        }
    }

    #[test]
    fn test_qgf_known_minimal_file_structure() {
        // Minimal valid QGF: graphics descriptor + 1 frame
        let mut qgf = Cursor::new(Vec::new());
        
        // Graphics descriptor
        let graphics = qgf::GraphicsDescriptor {
            version: 1,
            total_file_size: 0,
            image_width: 1,
            image_height: 1,
            frame_count: 1,
        };
        graphics.write(&mut qgf).unwrap();
        
        let bytes = qgf.into_inner();
        
        // Minimum size: 5 (header) + 18 (graphics) = 23 bytes
        assert!(bytes.len() >= 23, "QGF file too small: {}", bytes.len());
        
        // Verify header structure
        assert_eq!(bytes[0], 0x00); // Graphics descriptor type
        assert_eq!(bytes[1], 0xFF); // Inverted type
    }

    #[test]
    fn test_qgf_known_format_descriptors() {
        // Test that format bytes match expected values
        let format_mappings = vec![
            (ImageFormat::Rgb888, 0x09),
            (ImageFormat::Rgb565, 0x08),
            (ImageFormat::Pal256, 0x07),
            (ImageFormat::Pal16, 0x06),
            (ImageFormat::Pal4, 0x05),
            (ImageFormat::Pal2, 0x04),
            (ImageFormat::Mono256, 0x03),
            (ImageFormat::Mono16, 0x02),
            (ImageFormat::Mono4, 0x01),
            (ImageFormat::Mono2, 0x00),
        ];
        
        for (format, expected_byte) in format_mappings {
            let metadata = format.metadata();
            assert_eq!(metadata.image_format_byte, expected_byte,
                "Format byte mismatch for {:?}", format);
        }
    }

    // ==================== Known CLI Output Tests ====================
    // These test patterns that would come from actual CLI usage

    #[test]
    fn test_cli_output_header_file_generation() {
        let license = "// Copyright 2024 QMK\n";
        let var_name = "gfx_test_image";
        let byte_count = 256;
        
        let header = codegen::generate_header(var_name, byte_count, license);
        
        // Verify header contains expected elements
        assert!(header.contains("#pragma once"), "Missing header guard");
        assert!(header.contains("#include <qp.h>"), "Missing QP include");
        assert!(header.contains("extern"), "Missing extern declaration");
        assert!(header.contains(var_name), "Missing variable name");
        assert!(header.contains(&byte_count.to_string()), "Missing byte count");
    }

    #[test]
    fn test_cli_output_source_file_generation() {
        let license = "// Copyright 2024 QMK\n";
        let var_name = "gfx_test_image";
        let data = vec![0xFF, 0x00, 0xAA, 0x55];
        let metadata = "// 2x2 RGB565 image";
        
        let source = codegen::generate_source(var_name, &data, metadata, license);
        
        // Verify source contains expected elements
        assert!(source.contains("const uint8_t"), "Missing const declaration");
        assert!(source.contains(var_name), "Missing variable name");
        assert!(source.contains("clang-format"), "Missing clang-format pragmas");
        assert!(source.contains(metadata), "Missing metadata");
    }

    #[test]
    fn test_cli_output_byte_formatting() {
        // Test that byte formatting matches QMK output style
        let data = vec![0xFF, 0x00, 0xAA, 0x55, 0x12, 0x34, 0x56, 0x78];
        let formatted = codegen::format_bytes(&data, 4);
        
        // Should contain hex representation
        assert!(formatted.contains("0xFF"), "Missing 0xFF");
        assert!(formatted.contains("0x00"), "Missing 0x00");
        assert!(formatted.contains("0xAA"), "Missing 0xAA");
        
        // Should have commas
        assert!(formatted.contains(','), "Missing commas");
    }

    #[test]
    fn test_cli_known_output_qmk_example_1x1_image() {
        // Minimal test: 1x1 pixel in different formats
        let formats = vec![
            ImageFormat::Mono2,
            ImageFormat::Mono4,
            ImageFormat::Mono16,
            ImageFormat::Mono256,
            ImageFormat::Pal2,
            ImageFormat::Pal4,
            ImageFormat::Pal16,
            ImageFormat::Pal256,
        ];
        
        for format in formats {
            let pixel = vec![128];
            let metadata = format.metadata();
            let converted = convert_image_bytes(&pixel, 1, 1, &metadata);
            assert!(converted.is_ok(), "Failed to convert 1x1 image for {:?}", format);
        }
    }

    // ==================== Known Workflow Tests ====================
    // These test complete workflows as would be done by the CLI

    #[test]
    fn test_workflow_known_16x16_mono_image() {
        // Workflow: 16x16 monochrome image
        let mut pixels = Vec::new();
        for y in 0..16 {
            for x in 0..16 {
                // Checkerboard pattern
                pixels.push(if (x + y) % 2 == 0 { 255 } else { 0 });
            }
        }
        
        let format = ImageFormat::Mono256.metadata();
        let converted = convert_image_bytes(&pixels, 16, 16, &format).unwrap();
        assert_eq!(converted.pixel_data.len(), 256);
        
        let compressed = RleCompressor::compress(&converted.pixel_data);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, converted.pixel_data);
    }

    #[test]
    fn test_workflow_known_animated_gif_frame() {
        // Workflow: Single frame from animated GIF
        // Typical: 128x64 OLED with RGB565 (16-bit color)
        let frame_pixels = vec![0xFF; 128 * 64 * 3]; // RGB888 input
        
        let format = ImageFormat::Rgb565.metadata();
        let converted = convert_image_bytes(&frame_pixels, 128, 64, &format).unwrap();
        assert_eq!(converted.pixel_data.len(), 128 * 64 * 2);
        
        let compressed = RleCompressor::compress(&converted.pixel_data);
        assert!(compressed.len() < converted.pixel_data.len() / 2,
            "Animation frame should compress well for solid color");
    }

    #[test]
    fn test_workflow_known_palette_image_with_compression() {
        // Workflow: 32x32 palette image with RLE
        let pixels: Vec<u8> = (0..16).cycle().take(1024).collect();
        
        let format = ImageFormat::Pal16.metadata();
        let converted = convert_image_bytes(&pixels, 32, 32, &format).unwrap();
        
        let compressed = RleCompressor::compress(&converted.pixel_data);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, converted.pixel_data);
    }

    #[test]
    fn test_workflow_known_qgf_generation_complete() {
        // Complete workflow: Create minimal QGF file
        let mut qgf = Cursor::new(Vec::new());
        
        // 1. Graphics descriptor
        let graphics = qgf::GraphicsDescriptor {
            version: 1,
            total_file_size: 0,
            image_width: 8,
            image_height: 8,
            frame_count: 1,
        };
        graphics.write(&mut qgf).unwrap();
        
        // 2. Frame offset table
        let offset_position = qgf.position() as u32;
        let offsets = qgf::FrameOffsetDescriptor {
            offsets: vec![offset_position + 13],
        };
        offsets.write(&mut qgf).unwrap();
        
        // 3. Frame descriptor
        let frame = qgf::FrameDescriptor {
            format: 0x08,
            flags: 0,
            compression: 0x01,
            transparency_index: 0xFF,
            delay: 0,
        };
        frame.write(&mut qgf).unwrap();
        
        // 4. Frame data
        let data = qgf::DataDescriptor {
            data: vec![0xFF; 128],
        };
        data.write(&mut qgf).unwrap();
        
        let bytes = qgf.into_inner();
        assert!(bytes.len() > 0, "QGF file generation failed");
    }
}

// ==================== Regression Tests from Known Issues ====================

#[cfg(test)]
mod qmk_cli_regression_tests {
    use qmk_painter::RleCompressor;

    #[test]
    fn test_regression_rle_frame_boundary_1024() {
        // Known issue: compression fails at exactly 1024 bytes
        let data = vec![0xAA; 1024];
        let compressed = RleCompressor::compress(&data);
        let decompressed = RleCompressor::decompress(&compressed).unwrap();
        assert_eq!(decompressed, data);
    }

    #[test]
    fn test_regression_rle_animation_frame_transitions() {
        // Known issue: RLE fails with frame-to-frame transitions
        let frame1 = vec![0xFF; 512];
        let frame2 = vec![0xAA; 512];
        
        let compressed1 = RleCompressor::compress(&frame1);
        let compressed2 = RleCompressor::compress(&frame2);
        
        let decompressed1 = RleCompressor::decompress(&compressed1).unwrap();
        let decompressed2 = RleCompressor::decompress(&compressed2).unwrap();
        
        assert_eq!(decompressed1, frame1);
        assert_eq!(decompressed2, frame2);
    }

    #[test]
    fn test_regression_rgb565_endianness() {
        // Known issue: RGB565 byte order incorrect on some systems
        use qmk_painter::rgb_to565;
        
        let (msb, lsb) = rgb_to565(255, 255, 255);
        let value = u16::from_le_bytes([lsb, msb]);
        
        // All bits should be set for white
        assert_eq!(value, 0xFFFF, "RGB565 white should be 0xFFFF");
    }
}
